### ISSUE TITLE
Get Battle Information

### ISSUE THREAD

**Issue by alexcurtin** [preschian/gosugamers-dota2-api#1]
the /battle endpoint requires what query/string to return information about a particular match?

**Comment by preschian** [comment]
matchLink from recent results
```
/battle?link={matchLink}
```
example:
http://gosugamers-dota2-api.herokuapp.com/battle?link=/dota2/tournaments/14089-prodota-cup-17-eu/matches/167358-cyber-anji-vs-hive

tbh, this repo still unfinished. need some works 😅
